spring:
  datasource:
    url: jdbc:mysql://localhost:3306/final
    username: root
    password: 1234
  #jpa:
  #  show-sql: true

server:
  port: 9090
  servlet.context-path: /api

logging.level.root: error
